"""
LangGraph workflow definition for LinkedIn candidate sourcing.

This module defines the graph structure, state, and execution flow for an
agentic pipeline that converts user hiring requirements into LinkedIn
candidate search results.

Pipeline Overview:
    1. Accept user input (`user_prompt`)
    2. Generate a LinkedIn Boolean search query using an LLM
    3. Perform a Google X-ray search via Serper API
    4. Extract and return LinkedIn profile results

Core Components:
    - State:
        Shared data object passed between nodes (input → query → results)

    - Context:
        Runtime configuration for controlling execution behavior

    - Nodes:
        - build_search_query_linkedin: Generates Boolean query from user input
        - search_linkedin_profiles: Fetches LinkedIn profiles using Serper API

    - Graph:
        Defines the execution order and data flow between nodes

Usage:
    - Initialize the graph
    - Invoke with input state:
        graph.invoke({"user_prompt": "<hiring requirement>"})

    - Optional runtime config:
        graph.invoke(input_state, config={"configurable": {...}})

Notes:
    - Designed for extensibility (can add more nodes like ranking, enrichment)
    - Uses external APIs (LLM + Serper) for query generation and search
    - Does not perform data enrichment or validation by default

Dependencies:
    - LangGraph
    - requests
    - LLM API (configured via environment variables)
    - Serper API for search

Environment Variables:
    - LLM_BASE_URL
    - SERPER_BASE_URL
    - SERPER_API_KEY
    - XRAY_PREFIX

"""

from __future__ import annotations
from typing import Any, Dict, List
import json
from langgraph.graph import StateGraph, START, END
from langgraph.runtime import Runtime
from typing_extensions import TypedDict

# from dotenv import load_dotenv
import os

import requests

from prompt_templates.linkedin_query_prompt import LINKEDIN_QUERY_PROMPT
# from prompt_templates.user_intent_prompt import INTENT_CLASSIFIER_PROMPT

class Context(TypedDict):
    """
    Runtime configuration context for the LangGraph agent.

    This TypedDict defines configurable parameters that can be passed at
    graph initialization or invocation time. Unlike `State`, which carries
    data through the workflow, `Context` is used to control execution behavior,
    feature flags, and environment-specific settings.

    Fields:
        my_configurable_param (str):
            Example configurable parameter.
            Can be used to modify node behavior dynamically (e.g., toggle features,
            switch environments, adjust limits, or inject runtime configs).

    Usage:
        - Passed during graph invocation:
            graph.invoke(input_state, config={"configurable": {...}})

        - Accessed inside nodes via:
            runtime.context.get("my_configurable_param")

    Notes:
        - Context is read-only during execution
        - Ideal for passing non-user, system-level configurations
        - Helps separate business logic (State) from runtime behavior (Context)

    Reference:
        LangGraph Context Docs:
        https://langchain-ai.github.io/langgraph/cloud/how-tos/configuration_cloud/
    """
    
class State(TypedDict):
    """
    Shared state object passed between LangGraph nodes.

    This TypedDict defines the structure of data flowing through the agent pipeline.
    Each node reads from and writes to this state, enabling step-by-step data
    transformation (e.g., prompt → query → search results).

    Fields:
        user_prompt (str):
            Raw user input describing hiring requirements.
            Example: "Looking for JavaScript developers with React in India"

        linkedin_query (str):
            Boolean search query generated by the LLM for LinkedIn sourcing.
            Example: ('("Frontend Developer" OR "Javascript Developer") AND ("React") AND ("India")')

        linkedin_results (List[Dict]):
            List of LinkedIn profile search results fetched via Serper API.
            Each item typically contains:
                - title (str): Search result title
                - snippet (str): Short description
                - url (str): LinkedIn profile link

    Notes:
        - This state is mutable and shared across all LangGraph nodes
        - Each node is responsible for updating only relevant fields
        - Missing keys may cause runtime errors if not handled properly
        - Consider using `.get()` when accessing optional fields

    Reference:
        LangGraph State Docs:
        https://langchain-ai.github.io/langgraph/concepts/low_level/#state
    """
    user_prompt: str
    linkedin_query: str
    linkedin_results: List[str]    
    # google_query: str
    # google_results: list

def build_search_query_linkedin(state: State, runtime: Runtime[Context]) -> Dict[str, Any]:
    """
    Generate a LinkedIn Boolean search query from user input using an LLM.

    This function acts as a LangGraph node that transforms a natural language
    hiring requirement (`user_prompt`) into a structured LinkedIn search query.
    The generated query is stored back into the shared state under `linkedin_query`.

    Workflow:
        1. Extract `user_prompt` from the state
        2. Format the prompt using `LINKEDIN_QUERY_PROMPT`
        3. Send request to LLM API (streaming enabled)
        4. Aggregate streamed response chunks
        5. Store final query in state

    Args:
        state (State):
            Shared mutable state across LangGraph nodes.
            Expected to contain:
                - user_prompt (str): Raw hiring requirement input

        runtime (Runtime[Context]):
            LangGraph runtime context (currently unused).
            Can be used for logging, configuration, or metadata injection.

    Returns:
        Dict[str, Any]:
            Updated state containing:
                - linkedin_query (str): Generated LinkedIn Boolean search query

    Raises:
        requests.exceptions.RequestException:
            If the LLM API call fails

        json.JSONDecodeError:
            If streaming response contains invalid JSON

    Environment Variables:
        LLM_BASE_URL (str):
            Base URL of the LLM API (e.g., http://localhost:11434)

    Notes:
        - Uses streaming response (`iter_lines`) to handle token-wise generation
        - Assumes LLM returns line-delimited JSON with a `response` field
        - No validation is applied to the generated query (should be handled downstream)
    """  
    LLM_BASE_URL = os.getenv("LLM_BASE_URL")
    
    prompt = LINKEDIN_QUERY_PROMPT.format(
        user_input=state.get('user_prompt')
    )
    
    data = {
    "model": "qwen2.5",
    "prompt": prompt
    }
        
    response = requests.post(
        LLM_BASE_URL+"/api/generate", 
        json=data, 
        stream=True
    )
        
    full_response = ""
    
    for line in response.iter_lines():
        if line:
            chunk = json.loads(line)
            full_response += chunk.get("response", "")
    
    print("Response From LLM in[build_search_query_linkedin]::::::", full_response)
    
    state['linkedin_query'] = full_response
    
    return state

def search_linkedin_profiles(state: State, runtime: Runtime[Context]) -> Dict[str, Any]:
    """
    Fetch LinkedIn profile search results using Serper (Google Search API).

    This function acts as a LangGraph node that performs a Google X-ray search
    to retrieve LinkedIn profile URLs based on a previously generated Boolean query.
    It filters and stores relevant LinkedIn profile results into the shared state.

    Workflow:
        1. Read `linkedin_query` from state
        2. Prefix query with X-ray filter (e.g., site:linkedin.com/in)
        3. Send search request to Serper API
        4. Parse organic search results
        5. Filter only LinkedIn profile URLs
        6. Store structured results in state

    Args:
        state (State):
            Shared mutable state across LangGraph nodes.
            Expected to contain:
                - linkedin_query (str): Boolean search query generated by LLM

        runtime (Runtime[Context]):
            LangGraph runtime context (currently unused).
            Can be used for logging, tracing, or configuration injection.

    Returns:
        Dict[str, Any]:
            Updated state containing:
                - linkedin_results (List[Dict]): List of extracted LinkedIn profiles
                    Each item includes:
                        - title (str): Page title from search result
                        - snippet (str): Short description from search result
                        - url (str): LinkedIn profile URL

    Raises:
        requests.exceptions.RequestException:
            If the Serper API request fails

        ValueError:
            If response JSON is invalid or missing expected fields

    Environment Variables:
        SERPER_BASE_URL (str):
            Base URL for Serper API (e.g., https://google.serper.dev)

        SERPER_API_KEY (str):
            API key for authenticating Serper requests

        XRAY_PREFIX (str):
            Google X-ray search prefix (e.g., "site:linkedin.com/in")

    Notes:
        - Only results containing "linkedin.com/in" are included
        - Limits results to top 10 (configurable via payload)
        - Does not perform deduplication across multiple queries
        - Output is lightweight (no enrichment or structured parsing)
    """
    base_url =  os.getenv("SERPER_BASE_URL")
    x_ray_prefix = os.getenv("XRAY_PREFIX")
    
    endpoint = base_url+"/search"
    
    searchQuery = f'{x_ray_prefix} {state.get("linkedin_query")}'
    
    print("searchQuery::::::::::::", searchQuery)
    
    payload = {
        "q": searchQuery,
        "num": int(os.getenv("MAX_SEARCH_RESULTS")) | 10
    }

    headers = {
        "X-API-KEY": os.getenv("SERPER_API_KEY"),
        "Content-Type": "application/json"
    }

    response = requests.post(endpoint, json=payload, headers=headers)
    data = response.json()
    
    print("Data:::::::::::::::::::::::::", data)
    results = []

    for item in data.get("organic", []):
        link = item.get("link", "")
        
        if "linkedin.com/in" in link:
            results.append({
                "title": item.get("title"),
                "snippet": item.get("snippet"),
                "linkedin_url": link,
                "position": item.get('position')
            })
    print("results:::::::::::::::::::::", results)
    if(len(results)):
        state['linkedin_results'] = results
        
    return state

# Define Graph
graph = (
    StateGraph(State, context_schema=Context)
    # Nodes
    .add_node("build_search_query_linkedin", build_search_query_linkedin)
    .add_node("search_linkedin_profiles", search_linkedin_profiles)
    
    #Flow
    .add_edge(START, "build_search_query_linkedin")
    .add_edge("build_search_query_linkedin", "search_linkedin_profiles")
    .add_edge("search_linkedin_profiles", END)
    
    .compile(name="Talent Sourcing Graph")
)


